// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbsqlc

import (
	"database/sql"
	"time"
)

type Athlete struct {
	ID             int32
	Name           string
	Grade          int32
	PersonalRecord sql.NullString
	Events         sql.NullString
}

type Meet struct {
	ID          int32
	Name        string
	Date        time.Time
	Location    sql.NullString
	Description sql.NullString
}

type Result struct {
	ID        int32
	AthleteID int32
	MeetID    int32
	Time      string
	Place     int32
}
