// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package dbsqlc

import (
	"context"
	"database/sql"
	"time"
)

const createResult = `-- name: CreateResult :execresult
INSERT INTO results (athlete_id, meet_id, time, place)
VALUES (?, ?, ?, ?)
`

type CreateResultParams struct {
	AthleteID int32
	MeetID    int32
	Time      string
	Place     int32
}

func (q *Queries) CreateResult(ctx context.Context, arg CreateResultParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createResult,
		arg.AthleteID,
		arg.MeetID,
		arg.Time,
		arg.Place,
	)
}

const getAthleteByID = `-- name: GetAthleteByID :one
SELECT id, name, grade, COALESCE(personal_record, '') AS personal_record, COALESCE(events, '') AS events
FROM athletes
WHERE id = ?
`

type GetAthleteByIDRow struct {
	ID             int32
	Name           string
	Grade          int32
	PersonalRecord string
	Events         string
}

func (q *Queries) GetAthleteByID(ctx context.Context, id int32) (GetAthleteByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getAthleteByID, id)
	var i GetAthleteByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Grade,
		&i.PersonalRecord,
		&i.Events,
	)
	return i, err
}

const listAthletes = `-- name: ListAthletes :many
SELECT id, name, grade, COALESCE(personal_record, '') AS personal_record, COALESCE(events, '') AS events
FROM athletes
ORDER BY grade
`

type ListAthletesRow struct {
	ID             int32
	Name           string
	Grade          int32
	PersonalRecord string
	Events         string
}

func (q *Queries) ListAthletes(ctx context.Context) ([]ListAthletesRow, error) {
	rows, err := q.db.QueryContext(ctx, listAthletes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAthletesRow
	for rows.Next() {
		var i ListAthletesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Grade,
			&i.PersonalRecord,
			&i.Events,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMeets = `-- name: ListMeets :many
SELECT id, name, date, COALESCE(location, '') AS location, COALESCE(description, '') AS description
FROM meets
`

type ListMeetsRow struct {
	ID          int32
	Name        string
	Date        time.Time
	Location    string
	Description string
}

func (q *Queries) ListMeets(ctx context.Context) ([]ListMeetsRow, error) {
	rows, err := q.db.QueryContext(ctx, listMeets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMeetsRow
	for rows.Next() {
		var i ListMeetsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Date,
			&i.Location,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResultsByMeet = `-- name: ListResultsByMeet :many
SELECT id, athlete_id, meet_id, time, place
FROM results
WHERE meet_id = ?
ORDER BY place
`

func (q *Queries) ListResultsByMeet(ctx context.Context, meetID int32) ([]Result, error) {
	rows, err := q.db.QueryContext(ctx, listResultsByMeet, meetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Result
	for rows.Next() {
		var i Result
		if err := rows.Scan(
			&i.ID,
			&i.AthleteID,
			&i.MeetID,
			&i.Time,
			&i.Place,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
